server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # A magia está nesta linha: 
        # Tenta encontrar o ficheiro exato, se não encontrar, devolve o index.html
        try_files $uri $uri/ /index.html;
    }
}